import React, { useState } from 'react';
import { 
  Globe, 
  ShieldCheck, 
  Cpu, 
  Database, 
  HardDrive, 
  ArrowRight, 
  Info,
  X,
  FileCode,
  Network
} from 'lucide-react';

const NODE_METADATA = {
  dns: {
    title: "AWS Route 53 & CloudFront",
    service: "DNS & Content Delivery Network",
    spec: "Global Anycast DNS + 300+ Edge POPs",
    cost: "₹1,200 / month",
    ha: "100% SLA Global Anycast",
    terraform: "resource \"aws_route53_zone\" \"primary\" { ... }",
    security: "DDoS Mitigation (AWS Shield Standard) + ACM TLS 1.3"
  },
  alb: {
    title: "AWS Application Load Balancer (ALB) + WAF",
    service: "Elastic Ingress Traffic Router",
    spec: "Dual-AZ, Layer 7 SSL Termination, HTTP/2 Support",
    cost: "₹2,500 / month",
    ha: "Spans across us-east-1a and us-east-1b",
    terraform: "resource \"aws_lb\" \"external\" { load_balancer_type = \"application\" }",
    security: "AWS WAF Web ACL attached, TLS 1.3 Security Policy"
  },
  compute: {
    title: "FastAPI Compute Cluster (Auto Scaling Group)",
    service: "Containerized Backend API Service",
    spec: "Min: 2x, Desired: 2x, Max: 6x t3.medium EC2 instances",
    cost: "₹6,500 / month",
    ha: "Multi-Zone Auto Scaling across 2 private subnets",
    terraform: "resource \"aws_autoscaling_group\" \"api_asg\" { ... }",
    security: "Private subnet isolation (no public IP), IAM Instance Profile"
  },
  rds: {
    title: "AWS RDS PostgreSQL 15 (Multi-AZ)",
    service: "Managed Relational Database Engine",
    spec: "db.t3.medium, 50GB gp3 Auto-Scaling Storage to 200GB",
    cost: "₹11,000 / month",
    ha: "Synchronous Multi-AZ Standby with automated 60s failover",
    terraform: "resource \"aws_db_instance\" \"postgres\" { multi_az = true }",
    security: "Private DB Subnet Group, Storage encrypted with KMS AES256"
  },
  s3: {
    title: "Amazon S3 Object Storage",
    service: "Product Image & Asset Storage",
    spec: "Standard S3 Storage Class with Lifecycle Rules",
    cost: "₹800 / month",
    ha: "99.999999999% (11 9s) Durability across multiple facilities",
    terraform: "resource \"aws_s3_bucket\" \"assets\" { bucket = \"...\" }",
    security: "Block Public Access: Enabled, SSE-AES256 Server-side encryption"
  }
};

export default function ArchitectureView({ 
  alternatives, 
  selectedAlt, 
  setSelectedAlt, 
  onProceedToCode 
}) {
  const [activeNodeKey, setActiveNodeKey] = useState(null);
  const current = alternatives[selectedAlt] || alternatives.balanced;
  const inspectedNode = activeNodeKey ? NODE_METADATA[activeNodeKey] : null;

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      {/* Alternatives Tabs */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h2 className="text-xl font-bold text-white flex items-center space-x-2">
              <span>Cloud Architecture Alternatives</span>
              <span className="text-xs bg-blue-500/20 text-blue-300 border border-blue-500/30 px-2 py-0.5 rounded font-mono">
                Agent 6 • Cloud Topology
              </span>
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              Select an architecture trade-off profile generated by Cloud & Cost Optimization Agents.
            </p>
          </div>

          <button
            onClick={onProceedToCode}
            className="bg-blue-600 hover:bg-blue-500 text-white font-medium text-xs px-5 py-2.5 rounded-xl shadow-lg shadow-blue-600/20 transition flex items-center space-x-2 shrink-0"
          >
            <span>Inspect Generated Code</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>

        {/* 3 Architecture Selection Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
          {Object.entries(alternatives).map(([key, alt]) => {
            const isSelected = selectedAlt === key;
            const isRecommended = key === 'balanced';

            return (
              <div
                key={key}
                onClick={() => setSelectedAlt(key)}
                className={`cursor-pointer rounded-xl p-4 border transition-all relative flex flex-col justify-between ${
                  isSelected
                    ? 'bg-blue-950/40 border-blue-500 shadow-lg shadow-blue-500/10 ring-1 ring-blue-500'
                    : 'bg-slate-950/80 border-slate-800 hover:border-slate-700'
                }`}
              >
                {isRecommended && (
                  <span className="absolute -top-2.5 right-3 bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-[10px] font-bold px-2 py-0.5 rounded-full shadow">
                    RECOMMENDED DEFAULT
                  </span>
                )}

                <div className="space-y-2">
                  <div className="font-bold text-sm text-white">{alt.name}</div>
                  <div className="text-2xl font-extrabold text-emerald-400">
                    ₹{alt.cost_inr.toLocaleString()}
                    <span className="text-xs font-normal text-slate-400"> / mo</span>
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    {alt.description}
                  </p>
                </div>

                <div className="mt-4 pt-3 border-t border-slate-800/80 text-[11px] space-y-1 text-slate-300 font-mono">
                  <div className="flex justify-between">
                    <span className="text-slate-500">Performance:</span>
                    <span>{alt.performance}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500">Availability:</span>
                    <span className="text-blue-400">{alt.availability}</span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Interactive AWS Architecture Visualizer Canvas */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <Network className="w-5 h-5 text-indigo-400" />
            <h3 className="text-sm font-bold text-slate-200 uppercase tracking-wider">
              Interactive AWS Topology (Click nodes for Deep Inspector)
            </h3>
          </div>
          <span className="text-xs font-mono text-slate-400 bg-slate-800 px-2.5 py-1 rounded">
            Profile: {current.name}
          </span>
        </div>

        {/* AWS Topology Diagram Container */}
        <div className="bg-slate-950 border border-slate-800/90 rounded-xl p-6 relative overflow-hidden">
          <div className="grid grid-cols-1 md:grid-cols-5 gap-4 items-center">
            
            {/* Step 1: DNS & Edge */}
            <div 
              onClick={() => setActiveNodeKey('dns')}
              className="cursor-pointer p-4 rounded-xl bg-slate-900 border border-cyan-500/30 hover:border-cyan-400 transition flex flex-col items-center space-y-2 text-center group"
            >
              <Globe className="w-8 h-8 text-cyan-400 group-hover:scale-110 transition" />
              <span className="text-xs font-bold text-white">Route 53 & CloudFront</span>
              <span className="text-[10px] text-cyan-400 font-mono flex items-center space-x-1">
                <Info className="w-3 h-3" />
                <span>Click to inspect</span>
              </span>
            </div>

            {/* Connection 1 */}
            <div className="hidden md:flex justify-center text-blue-500/50">
              <ArrowRight className="w-6 h-6 animate-pulse" />
            </div>

            {/* Step 2: ALB + WAF */}
            <div 
              onClick={() => setActiveNodeKey('alb')}
              className="cursor-pointer p-4 rounded-xl bg-slate-900 border border-indigo-500/30 hover:border-indigo-400 transition flex flex-col items-center space-y-2 text-center group"
            >
              <ShieldCheck className="w-8 h-8 text-indigo-400 group-hover:scale-110 transition" />
              <span className="text-xs font-bold text-white">ALB + AWS WAF</span>
              <span className="text-[10px] text-indigo-400 font-mono flex items-center space-x-1">
                <Info className="w-3 h-3" />
                <span>Click to inspect</span>
              </span>
            </div>

            {/* Connection 2 */}
            <div className="hidden md:flex justify-center text-indigo-500/50">
              <ArrowRight className="w-6 h-6 animate-pulse" />
            </div>

            {/* Step 3: Compute */}
            <div 
              onClick={() => setActiveNodeKey('compute')}
              className="cursor-pointer p-4 rounded-xl bg-slate-900 border border-purple-500/30 hover:border-purple-400 transition flex flex-col items-center space-y-2 text-center group"
            >
              <Cpu className="w-8 h-8 text-purple-400 group-hover:scale-110 transition" />
              <span className="text-xs font-bold text-white">FastAPI ASG</span>
              <span className="text-[10px] text-purple-400 font-mono flex items-center space-x-1">
                <Info className="w-3 h-3" />
                <span>Click to inspect</span>
              </span>
            </div>

          </div>

          {/* Bottom Row: Data Layer (RDS & S3) */}
          <div className="mt-6 pt-6 border-t border-slate-800/80 grid grid-cols-1 md:grid-cols-2 gap-4">
            
            <div 
              onClick={() => setActiveNodeKey('rds')}
              className="cursor-pointer bg-slate-900/90 border border-emerald-500/30 hover:border-emerald-400 transition rounded-xl p-4 flex items-center space-x-4 group"
            >
              <div className="w-12 h-12 rounded-lg bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center shrink-0">
                <Database className="w-6 h-6 text-emerald-400 group-hover:scale-110 transition" />
              </div>
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-bold text-white">AWS RDS PostgreSQL 15 (Multi-AZ)</h4>
                  <span className="text-[10px] text-emerald-400 font-mono">Inspect ➔</span>
                </div>
                <p className="text-[11px] text-slate-400 mt-0.5">
                  Synchronous multi-zone standby failover, isolated in private DB subnet.
                </p>
              </div>
            </div>

            <div 
              onClick={() => setActiveNodeKey('s3')}
              className="cursor-pointer bg-slate-900/90 border border-cyan-500/30 hover:border-cyan-400 transition rounded-xl p-4 flex items-center space-x-4 group"
            >
              <div className="w-12 h-12 rounded-lg bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center shrink-0">
                <HardDrive className="w-6 h-6 text-cyan-400 group-hover:scale-110 transition" />
              </div>
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-bold text-white">Amazon S3 Encrypted Storage</h4>
                  <span className="text-[10px] text-cyan-400 font-mono">Inspect ➔</span>
                </div>
                <p className="text-[11px] text-slate-400 mt-0.5">
                  SSE-AES256 server-side encryption, Block Public Access enabled.
                </p>
              </div>
            </div>

          </div>
        </div>
      </div>

      {/* Node Inspector Modal */}
      {inspectedNode && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center p-4 z-50 backdrop-blur-sm">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6 max-w-lg w-full shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div>
                <h3 className="text-base font-bold text-white">{inspectedNode.title}</h3>
                <span className="text-xs text-blue-400 font-mono">{inspectedNode.service}</span>
              </div>
              <button 
                onClick={() => setActiveNodeKey(null)}
                className="p-1.5 rounded-lg bg-slate-800 text-slate-400 hover:text-white"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 space-y-1">
                <div className="text-slate-400 font-mono uppercase text-[10px]">Specifications & Capacity:</div>
                <div className="text-white font-medium">{inspectedNode.spec}</div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                  <div className="text-slate-400 text-[10px] font-mono">Estimated Cost:</div>
                  <div className="text-emerald-400 font-bold font-mono text-sm mt-0.5">{inspectedNode.cost}</div>
                </div>
                <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                  <div className="text-slate-400 text-[10px] font-mono">High Availability:</div>
                  <div className="text-blue-400 font-medium font-mono text-[11px] mt-0.5">{inspectedNode.ha}</div>
                </div>
              </div>

              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 space-y-1">
                <div className="text-slate-400 font-mono uppercase text-[10px]">Security Controls:</div>
                <div className="text-slate-200">{inspectedNode.security}</div>
              </div>

              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 space-y-1 font-mono">
                <div className="text-slate-400 uppercase text-[10px] flex items-center space-x-1">
                  <FileCode className="w-3.5 h-3.5 text-purple-400" />
                  <span>Terraform IaC Mapping:</span>
                </div>
                <div className="text-purple-300 text-[11px] bg-slate-900 p-2 rounded border border-slate-800">
                  {inspectedNode.terraform}
                </div>
              </div>
            </div>

            <div className="pt-2 flex justify-end">
              <button
                onClick={() => setActiveNodeKey(null)}
                className="text-xs px-4 py-2 rounded-lg bg-blue-600 text-white font-medium hover:bg-blue-500"
              >
                Done
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
