import React, { useState } from 'react';
import { 
  Code, 
  Copy, 
  Check, 
  ChevronRight, 
  Database, 
  Cloud, 
  Server, 
  FileJson, 
  Layers, 
  TerminalSquare 
} from 'lucide-react';

// ── Domain-aware code samples ─────────────────────────────────────────────────
const CODE_TABS = [
  {
    id: 'fastapi',
    label: 'FastAPI Backend',
    icon: Server,
    language: 'Python',
    domain: (domain) => {
      const domainMap = {
        food_delivery: `# FastAPI — Food Delivery Platform (25,000 users)
# Auto-generated by AI Product Architect (Member 3)

from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from typing import List, Optional
import uvicorn

app = FastAPI(title="FoodRush API", version="2.0.0", docs_url="/api/docs")

app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

# ─── Restaurant Routes ────────────────────────────────────────────────
@app.get("/api/restaurants", response_model=List[RestaurantSchema])
async def list_restaurants(city: str, category: Optional[str] = None, db: Session = Depends(get_db)):
    """Return all restaurants, optionally filtered by food category."""
    query = db.query(Restaurant).filter(Restaurant.city == city, Restaurant.is_active == True)
    if category:
        query = query.filter(Restaurant.category == category)
    return query.order_by(Restaurant.rating.desc()).limit(50).all()

@app.get("/api/restaurants/{restaurant_id}/menu")
async def get_menu(restaurant_id: str, db: Session = Depends(get_db)):
    menu = db.query(MenuItem).filter(MenuItem.restaurant_id == restaurant_id).all()
    if not menu:
        raise HTTPException(status_code=404, detail="Restaurant not found")
    return {"items": menu, "count": len(menu)}

# ─── Order Routes ─────────────────────────────────────────────────────
@app.post("/api/orders", response_model=OrderSchema, status_code=status.HTTP_201_CREATED)
async def create_order(order_in: OrderCreateSchema, current_user = Depends(get_current_user), db: Session = Depends(get_db)):
    """Create order with real-time driver assignment."""
    order = Order(**order_in.dict(), user_id=current_user.id, status="PENDING")
    db.add(order); db.commit(); db.refresh(order)
    assign_nearest_driver.delay(order.id)  # Celery task
    return order

@app.websocket("/ws/orders/{order_id}")
async def track_order(websocket: WebSocket, order_id: str):
    """WebSocket: real-time delivery tracking (GPS location stream)."""
    await manager.connect(websocket)
    try:
        while True:
            location = await get_driver_location(order_id)
            await websocket.send_json({"location": location, "status": "EN_ROUTE"})
            await asyncio.sleep(5)
    except WebSocketDisconnect:
        manager.disconnect(websocket)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)`,

        lms: `# FastAPI — Learning Management System (15,000 users)
# Auto-generated by AI Product Architect (Member 3)

from fastapi import FastAPI, Depends, HTTPException, status, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
import uvicorn

app = FastAPI(title="EduCloud LMS API", version="1.5.0")

app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

# ─── Course Routes ────────────────────────────────────────────────────
@app.get("/api/courses", summary="Paginated course catalogue")
async def list_courses(page: int = 1, limit: int = 20, category: Optional[str] = None):
    """Full-text search enabled course listing with instructor metadata."""
    offset = (page - 1) * limit
    return {"courses": courses[offset:offset+limit], "total": len(courses), "page": page}

@app.post("/api/courses/{course_id}/lessons", status_code=201)
async def upload_lesson(course_id: str, video: UploadFile = File(...), current_user=Depends(require_instructor)):
    """Instructors upload lesson videos — stored in S3 CloudFront CDN."""
    s3_url = await upload_to_s3(video, bucket="educloud-lessons")
    lesson = Lesson(course_id=course_id, video_url=s3_url, uploaded_by=current_user.id)
    return lesson

# ─── Progress Tracking ────────────────────────────────────────────────
@app.post("/api/courses/{course_id}/lessons/{lesson_id}/progress")
async def mark_progress(course_id: str, lesson_id: str, progress: int, current_user=Depends(get_current_user)):
    """Track lesson completion percentage for certifications."""
    enrollment = get_enrollment_or_404(current_user.id, course_id)
    enrollment.progress_map[lesson_id] = progress
    if all(p >= 80 for p in enrollment.progress_map.values()):
        issue_certificate.delay(current_user.id, course_id)
    return {"status": "updated", "overall_completion": compute_overall(enrollment)}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)`,

        default: `# FastAPI — E-Commerce Platform (50,000 users, ₹30,000/mo budget)
# Auto-generated by AI Product Architect (Member 3)
# Section 41 Demo: CloudScale E-Commerce

from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import OAuth2PasswordBearer
from sqlalchemy.orm import Session
from typing import List
import uvicorn

app = FastAPI(title="CloudScale E-Commerce API", version="3.1.0", docs_url="/api/docs")

app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/auth/login")

# ─── Auth Routes ──────────────────────────────────────────────────────
@app.post("/api/auth/register", status_code=status.HTTP_201_CREATED)
async def register(user_in: UserCreateSchema, db: Session = Depends(get_db)):
    if db.query(User).filter_by(email=user_in.email).first():
        raise HTTPException(status_code=400, detail="Email already registered")
    user = User(email=user_in.email, password_hash=bcrypt.hash(user_in.password))
    db.add(user); db.commit()
    return {"message": "Account created", "user_id": str(user.id)}

@app.post("/api/auth/login")
async def login(credentials: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    user = authenticate_user(db, credentials.username, credentials.password)
    if not user:
        raise HTTPException(status_code=401, detail="Invalid credentials")
    token = create_jwt({"sub": str(user.id)}, expires_minutes=60)
    return {"access_token": token, "token_type": "bearer"}

# ─── Product Routes ───────────────────────────────────────────────────
@app.get("/api/products", response_model=List[ProductSchema])
async def get_products(page: int = 1, category: str = None, db: Session = Depends(get_db)):
    products = db.query(Product).filter(Product.is_active == True)
    if category:
        products = products.filter(Product.category == category)
    return products.offset((page-1)*20).limit(20).all()

# ─── Cart & Orders ────────────────────────────────────────────────────
@app.post("/api/orders", response_model=OrderSchema)
async def create_order(order_in: OrderCreateSchema, current_user=Depends(get_current_user), db: Session = Depends(get_db)):
    order = Order(**order_in.dict(), user_id=current_user.id, status="PENDING")
    db.add(order); db.commit()
    return order

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000, workers=4)`
      };
      return domainMap[domain] || domainMap['default'];
    }
  },
  {
    id: 'postgresql',
    label: 'PostgreSQL Schema',
    icon: Database,
    language: 'SQL',
    domain: (domain) => {
      const domainMap = {
        food_delivery: `-- PostgreSQL Schema — Food Delivery Platform
-- Auto-generated by AI Product Architect (db_generator.py)

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";  -- Geo-location for drivers

-- Users & Auth
CREATE TABLE users (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    phone       VARCHAR(15) UNIQUE NOT NULL,
    email       VARCHAR(255) UNIQUE,
    name        VARCHAR(100) NOT NULL,
    address     JSONB DEFAULT '{}',
    created_at  TIMESTAMP DEFAULT NOW()
);

-- Restaurants
CREATE TABLE restaurants (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        VARCHAR(200) NOT NULL,
    city        VARCHAR(100) NOT NULL,
    category    VARCHAR(50),
    rating      NUMERIC(2,1) DEFAULT 4.0 CHECK (rating BETWEEN 1 AND 5),
    location    GEOGRAPHY(POINT, 4326),  -- PostGIS geo-point
    is_active   BOOLEAN DEFAULT TRUE,
    INDEX idx_restaurants_city (city),
    INDEX idx_restaurants_category (category)
);

-- Menu Items
CREATE TABLE menu_items (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    restaurant_id   UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    name            VARCHAR(200) NOT NULL,
    price           NUMERIC(8,2) NOT NULL CHECK (price >= 0),
    is_available    BOOLEAN DEFAULT TRUE
);

-- Orders with geo-tracking
CREATE TABLE orders (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id),
    restaurant_id   UUID NOT NULL REFERENCES restaurants(id),
    status          VARCHAR(30) DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACCEPTED','PREPARING','EN_ROUTE','DELIVERED','CANCELLED')),
    total_amount    NUMERIC(10,2) NOT NULL,
    delivery_address JSONB NOT NULL,
    created_at      TIMESTAMP DEFAULT NOW()
);`,

        lms: `-- PostgreSQL Schema — Learning Management System
-- Auto-generated by AI Product Architect (db_generator.py)

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users (students & instructors)
CREATE TABLE users (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(255) UNIQUE NOT NULL,
    role        VARCHAR(20) DEFAULT 'STUDENT' CHECK (role IN ('STUDENT','INSTRUCTOR','ADMIN')),
    created_at  TIMESTAMP DEFAULT NOW()
);

-- Courses
CREATE TABLE courses (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title           VARCHAR(300) NOT NULL,
    description     TEXT,
    instructor_id   UUID NOT NULL REFERENCES users(id),
    category        VARCHAR(100),
    price_inr       NUMERIC(10,2) DEFAULT 0,
    is_published    BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP DEFAULT NOW()
);

-- Lessons (stored in S3)
CREATE TABLE lessons (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    course_id   UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title       VARCHAR(300) NOT NULL,
    video_url   TEXT,           -- S3 CloudFront CDN URL
    duration_s  INTEGER DEFAULT 0,
    order_idx   SMALLINT NOT NULL,
    UNIQUE (course_id, order_idx)
);

-- Enrollment & Progress
CREATE TABLE enrollments (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id),
    course_id       UUID NOT NULL REFERENCES courses(id),
    progress_map    JSONB DEFAULT '{}',  -- {lesson_id: completion_pct}
    certificate_url TEXT,
    enrolled_at     TIMESTAMP DEFAULT NOW(),
    UNIQUE (user_id, course_id)
);`,

        default: `-- PostgreSQL Schema — CloudScale E-Commerce Platform
-- Auto-generated by AI Product Architect (db_generator.py)
-- Supports 50,000 concurrent users with PgBouncer connection pooling

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";  -- Full-text search

-- Users table with PII vault
CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email           VARCHAR(255) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    full_name       VARCHAR(100),
    phone           VARCHAR(20),
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_users_email ON users(email);

-- Products table with FTS index
CREATE TABLE products (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        VARCHAR(500) NOT NULL,
    description TEXT,
    price_inr   NUMERIC(12,2) NOT NULL CHECK (price_inr >= 0),
    stock_qty   INTEGER DEFAULT 0 CHECK (stock_qty >= 0),
    category    VARCHAR(100),
    image_url   TEXT,
    is_active   BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_fts ON products USING GIN (to_tsvector('english', name || ' ' || COALESCE(description, '')));

-- Orders table (normalized for analytics)
CREATE TABLE orders (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status          VARCHAR(30) DEFAULT 'PENDING' CHECK (status IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),
    total_amount    NUMERIC(14,2) NOT NULL CHECK (total_amount >= 0),
    shipping_address JSONB NOT NULL,
    payment_ref     VARCHAR(200),
    created_at      TIMESTAMP DEFAULT NOW()
);

CREATE TABLE order_items (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id    UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id  UUID NOT NULL REFERENCES products(id),
    quantity    SMALLINT NOT NULL CHECK (quantity > 0),
    unit_price  NUMERIC(12,2) NOT NULL
);
CREATE INDEX idx_order_items_order ON order_items(order_id);`
      };
      return domainMap[domain] || domainMap['default'];
    }
  },
  {
    id: 'terraform',
    label: 'Terraform (AWS)',
    icon: Cloud,
    language: 'HCL',
    domain: () => `# AWS Terraform IaC — CloudScale E-Commerce
# Auto-generated by AI Product Architect (tf_generator.py)
# Sections 31 & 41: Multi-AZ Production-Grade Infrastructure

terraform {
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
  backend "s3" {
    bucket = "ai-architect-tf-state"
    key    = "ecommerce/terraform.tfstate"
    region = "ap-south-1"
  }
}

provider "aws" {
  region = var.aws_region
  default_tags { tags = { Project = "CloudScale", ManagedBy = "AI-Product-Architect" } }
}

# ── VPC & Networking ──────────────────────────────────────────────────
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"
  name    = "ecommerce-vpc"
  cidr    = "10.0.0.0/16"
  azs             = ["ap-south-1a", "ap-south-1b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]
  enable_nat_gateway   = true
  single_nat_gateway   = false  # HA: one per AZ
}

# ── Application Load Balancer ─────────────────────────────────────────
resource "aws_lb" "main" {
  name               = "ecommerce-alb"
  load_balancer_type = "application"
  subnets            = module.vpc.public_subnets
  security_groups    = [aws_security_group.alb_sg.id]
  enable_deletion_protection = true
}

# ── Auto Scaling Group (EC2 t3.medium) ───────────────────────────────
resource "aws_autoscaling_group" "app_asg" {
  name                = "ecommerce-asg"
  vpc_zone_identifier = module.vpc.private_subnets
  target_group_arns   = [aws_lb_target_group.app.arn]
  min_size         = 2
  max_size         = 20
  desired_capacity = 4
  launch_template {
    id      = aws_launch_template.app.id
    version = "$Latest"
  }
  tag { key = "Role"; value = "AppServer"; propagate_at_launch = true }
}

# ── RDS PostgreSQL (Multi-AZ) ─────────────────────────────────────────
resource "aws_db_instance" "postgres" {
  identifier           = "ecommerce-db"
  engine               = "postgres"
  engine_version       = "16.2"
  instance_class       = "db.t3.medium"
  allocated_storage    = 100
  storage_encrypted    = true
  multi_az             = true               # HA: automatic failover
  db_subnet_group_name = aws_db_subnet_group.rds.name
  vpc_security_group_ids = [aws_security_group.rds_sg.id]
  backup_retention_period = 7
  skip_final_snapshot  = false
}

# ── S3 Bucket (Product Images) ────────────────────────────────────────
resource "aws_s3_bucket" "images" {
  bucket = "cloudscale-product-images-\${var.env}"
}
resource "aws_s3_bucket_public_access_block" "images" {
  bucket                  = aws_s3_bucket.images.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Outputs
output "alb_dns"    { value = aws_lb.main.dns_name }
output "rds_host"   { value = aws_db_instance.postgres.address }
output "s3_bucket"  { value = aws_s3_bucket.images.bucket }`
  },
  {
    id: 'docker',
    label: 'Docker Compose',
    icon: Layers,
    language: 'YAML',
    domain: () => `# docker-compose.yml — Local Development Stack
# Auto-generated by AI Product Architect (docker_generator.py)
# Run: docker compose up -d

version: "3.9"

networks:
  cloudscale_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:

services:
  # ── FastAPI Application ────────────────────────────────
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloudscale-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://cs_user:cs_pass@postgres:5432/cloudscale"
      REDIS_URL: "redis://redis:6379/0"
      SECRET_KEY: "dev-secret-change-in-prod"
      ENVIRONMENT: "development"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks: [cloudscale_net]
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # ── React Frontend ─────────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloudscale-ui
    ports:
      - "3000:80"
    depends_on: [api]
    networks: [cloudscale_net]

  # ── PostgreSQL 16 ──────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: cloudscale-db
    environment:
      POSTGRES_DB: cloudscale
      POSTGRES_USER: cs_user
      POSTGRES_PASSWORD: cs_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./architecture/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cs_user -d cloudscale"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [cloudscale_net]

  # ── Redis (Session / Cart Cache) ───────────────────────
  redis:
    image: redis:7-alpine
    container_name: cloudscale-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks: [cloudscale_net]

  # ── PgAdmin (Dev DB Browser) ───────────────────────────
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cloudscale-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cloudscale.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on: [postgres]
    networks: [cloudscale_net]`
  },
  {
    id: 'pytest',
    label: 'Automated Tests',
    icon: TerminalSquare,
    language: 'Python',
    domain: () => `# tests/test_suite.py — Automated Validation Test Suite
# Auto-generated by AI Product Architect
# Run: pytest tests/ -v --tb=short

import pytest
import asyncio
import httpx
from typing import Generator

BASE_URL = "http://localhost:8000"

# ─── Fixtures ────────────────────────────────────────────────────────
@pytest.fixture
def auth_token(client) -> str:
    """Get JWT for test user — auto-created if not exists."""
    resp = client.post("/api/auth/register", json={
        "email": "test_student@cloudscale.dev",
        "password": "TestP@ss123!",
        "full_name": "Test Student"
    })
    assert resp.status_code in [201, 400]  # 400 if already registered
    login = client.post("/api/auth/login", data={
        "username": "test_student@cloudscale.dev",
        "password": "TestP@ss123!"
    })
    assert login.status_code == 200
    return login.json()["access_token"]

# ─── REQ-001: Authentication ──────────────────────────────────────────
def test_auth_register(client):
    """REQ-001: Users can register with email and password."""
    resp = client.post("/api/auth/register", json={
        "email": "new_user@test.com",
        "password": "Secure@1234"
    })
    assert resp.status_code == 201
    assert "user_id" in resp.json()

def test_auth_jwt(client, auth_token):
    """REQ-001: JWT token is valid and has correct claims."""
    headers = {"Authorization": f"Bearer {auth_token}"}
    resp = client.get("/api/users/me", headers=headers)
    assert resp.status_code == 200
    data = resp.json()
    assert "email" in data
    assert "id" in data

# ─── REQ-002: Product Catalog ─────────────────────────────────────────
def test_catalog_fetch(client):
    """REQ-002: Product catalog returns paginated results."""
    resp = client.get("/api/products?page=1")
    assert resp.status_code == 200
    data = resp.json()
    assert isinstance(data, list)
    assert len(data) <= 20  # Max 20 per page

def test_catalog_category_filter(client):
    """REQ-002: Category filter returns only matching products."""
    resp = client.get("/api/products?category=Electronics")
    assert resp.status_code == 200
    for product in resp.json():
        assert product["category"] == "Electronics"

# ─── REQ-003: Cart & Order Flow ───────────────────────────────────────
def test_order_flow(client, auth_token):
    """REQ-003: User can create an order with at least one product."""
    headers = {"Authorization": f"Bearer {auth_token}"}
    payload = {
        "items": [{"product_id": "test-product-uuid", "quantity": 2}],
        "shipping_address": {"city": "Bangalore", "pin": "560001"}
    }
    resp = client.post("/api/orders", json=payload, headers=headers)
    assert resp.status_code == 201
    order = resp.json()
    assert order["status"] == "PENDING"
    assert "id" in order

# ─── REQ-004: Scalability (Simulated) ────────────────────────────────
@pytest.mark.asyncio
async def test_stress_50k():
    """REQ-004: API can serve concurrent product requests."""
    async with httpx.AsyncClient(base_url=BASE_URL) as ac:
        tasks = [ac.get("/api/products") for _ in range(100)]
        results = await asyncio.gather(*tasks, return_exceptions=True)
    success_count = sum(1 for r in results if hasattr(r, 'status_code') and r.status_code == 200)
    assert success_count >= 95, f"Only {success_count}/100 requests succeeded"

# ─── REQ-005: High Availability ──────────────────────────────────────
def test_az_failover(client):
    """REQ-005: API health endpoint responds in < 500ms."""
    import time
    start = time.time()
    resp = client.get("/health")
    elapsed_ms = (time.time() - start) * 1000
    assert resp.status_code == 200
    assert elapsed_ms < 500, f"Health check took {elapsed_ms:.0f}ms (>500ms)"
    assert resp.json()["status"] == "healthy"`
  }
];

export default function CodePreview({ domain = 'ecommerce', generatedCode }) {
  const [activeTab, setActiveTab] = useState('fastapi');
  const [copied, setCopied] = useState(false);

  const activeTabData = CODE_TABS.find(t => t.id === activeTab);
  const domainKey = domain === 'ecommerce' ? 'default' : domain;
  const currentCode = typeof activeTabData?.domain === 'function'
    ? activeTabData.domain(domainKey)
    : '';

  const handleCopy = () => {
    navigator.clipboard.writeText(currentCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-4 max-w-5xl mx-auto">
      {/* Header */}
      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-5 shadow-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <div className="flex items-center space-x-2">
              <h2 className="text-lg font-bold text-white">Generated Code Preview</h2>
              <span className="text-xs bg-blue-500/20 text-blue-300 border border-blue-500/30 px-2 py-0.5 rounded font-mono">
                Code Generation
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Full-stack code auto-generated by AI Product Architect based on parsed requirements.
            </p>
          </div>
          <div className="flex items-center space-x-2 text-xs">
            <span className="bg-slate-800 text-slate-300 border border-slate-700 px-2.5 py-1.5 rounded-lg font-mono">
              Domain: <span className="text-cyan-400 font-bold capitalize">{domain === 'default' ? 'E-Commerce' : domain.replace('_', ' ')}</span>
            </span>
          </div>
        </div>

        {/* Tab Selector */}
        <div className="flex flex-wrap items-center gap-1.5 mt-4">
          {CODE_TABS.map(tab => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center space-x-1.5 text-xs px-3 py-2 rounded-xl border font-medium transition ${
                  isActive
                    ? 'bg-blue-600 text-white border-blue-500'
                    : 'bg-slate-950 text-slate-400 border-slate-800 hover:text-slate-200 hover:bg-slate-800'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Code Pane */}
      <div className="bg-slate-950 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl">
        {/* Code header bar */}
        <div className="flex items-center justify-between px-5 py-3 bg-slate-900/80 border-b border-slate-800">
          <div className="flex items-center space-x-3 text-xs text-slate-400">
            <div className="flex space-x-1.5">
              <div className="w-3 h-3 rounded-full bg-red-500/70" />
              <div className="w-3 h-3 rounded-full bg-amber-500/70" />
              <div className="w-3 h-3 rounded-full bg-emerald-500/70" />
            </div>
            <span className="font-mono text-slate-400 border border-slate-700 px-2 py-0.5 rounded">
              {activeTabData?.language || 'Code'}
            </span>
            <span className="text-slate-600">•</span>
            <span>{activeTabData?.label}</span>
          </div>
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 text-xs text-slate-400 hover:text-white bg-slate-800 hover:bg-slate-700 border border-slate-700 px-2.5 py-1.5 rounded-lg transition"
          >
            {copied ? <><Check className="w-3.5 h-3.5 text-emerald-400" /><span>Copied!</span></> : <><Copy className="w-3.5 h-3.5" /><span>Copy</span></>}
          </button>
        </div>

        {/* Code content */}
        <div className="overflow-x-auto max-h-[580px]">
          <pre className="text-xs font-mono text-emerald-300 p-5 whitespace-pre leading-relaxed">
            {currentCode}
          </pre>
        </div>
      </div>
    </div>
  );
}
